version: '2'
services:
    healthpoints-app:
        image: healthpoints
        external_links:
            - healthpoints-postgresql:postgresql
            - healthpoints-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/healthpoints
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    healthpoints-postgresql:
        extends:
            file: postgresql.yml
            service: healthpoints-postgresql
    healthpoints-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: healthpoints-elasticsearch
